### ISSUE TITLE
Upgrading from 0.7.0 to 0.8.0 yields "incompatible"

### ISSUE THREAD

**Issue by Git-Forked** [soupslurpr/AppVerifier#157] opened 2024-07-13 05:46 UTC
OS:  Android 10
Device: Samsung A01

**Comment by soupslurpr** [comment] 2024-07-13 05:48
Can you elaborate? What do you mean "incompatible"?

**Comment by soupslurpr** [comment] 2024-07-13 05:57
Also what device?

**Comment by Git-Forked** [comment] 2024-07-13 07:41
When installing it, the OS says in a popup "incompatible".
Device: Samsung A01

**Comment by Git-Forked** [comment] 2024-07-13 07:46
In some testing, I tried to uninstall the 0.7.0 and then tried to install the 0.8.0, however I get the same "incompatible".
I thought perhaps it was a signing key issue, however that does not seem so.

**Comment by soupslurpr** [comment] 2024-07-13 07:47
FYI that phone should have an update to Android 11.

**Comment by soupslurpr** [comment] 2024-07-13 07:47
But AppVerifier should work on Android 10. Could you try updating it and see what happens?

**Comment by Git-Forked** [comment] 2024-07-13 07:49
> FYI that phone should have an update to Android 11.

No, it doesn't, because it is a Tracfone brand, and those don't receive updates.

**Comment by soupslurpr** [comment] 2024-07-13 07:51
Ah rip. On the install screen can you see the app icon of AppVerifier?

**Comment by Git-Forked** [comment] 2024-07-13 07:55
I am installing it through Obtainium app. 
I see the icon in the popup that says " Do you want to install this application?"

**Comment by Git-Forked** [comment] 2024-07-13 08:00
To rule out Obtainium being an issue, I have downloaded the apk directly from:  
https://github.com/soupslurpr/AppVerifier/releases/download/0.8.0/AppVerifier-0.8.0.apk

This time instead of getting the error "incompatible", it instead say:  "App not installed."

**Comment by soupslurpr** [comment] 2024-07-13 08:09
Could you try this staging apk?
[app-staging.zip](https://github.com/user-attachments/files/16201344/app-staging.zip)

**Comment by Git-Forked** [comment] 2024-07-13 08:20
I would prefer not to.  I don't know what it is, and you haven't told me anything about it.  I'm not in the habit of just installing random things at someone's request.  This is not a development phone, it is my daily phone.

**Comment by Git-Forked** [comment] 2024-07-13 08:27
VirusTotal reports this file as malicious also. Perhaps a false positive, but as I said before I don't know anything about this file or where it comes from. 

https://www.virustotal.com/gui/url/2332321a3035ba414d1cb754b395bf0146b3f89c69cde4582f86b917ad6ba846?nocache=1

```Antiy-AVL     Malicious     Forcepoint ThreatSeeker     Suspicious```

**Comment by soupslurpr** [comment] 2024-07-13 08:27
Sorry if it wasn't clear, it's just AppVerifier with an addition reverted that I thought might've been causing the issue. Specifically https://github.com/soupslurpr/AppVerifier/blob/6aa73cb516e150eadc8a00f11470ab8697828c06/app/build.gradle.kts#L22

**Comment by soupslurpr** [comment] 2024-07-13 08:31
I can assure you it is not malicious and originates from my laptop. Be mindful that anti-virus software often has false positives and shouldn't be relied upon for detecting malware.

**Comment by soupslurpr** [comment] 2024-07-20 19:54
Did you try it?

**Comment by soupslurpr** [comment] 2024-07-26 07:54
Since I haven't gotten a response from you, I'm going to close this issue. I can't help you without your help. If you decide to respond then I'll open it again.

**Closed by soupslurpr** 2024-07-26 07:54 UTC

**Comment by samvde** [comment] 2024-08-03 23:27
I had this issue on a new install.  The staging  app fixed it.

**Comment by soupslurpr** [comment] 2024-08-03 23:40
@samvde thanks for testing, this means the device or OS you are using is 32-bit. Could you tell me what device and OS you are having this issue on?

**Comment by samvde** [comment] 2024-08-04 03:00
Sure, it is a Samsung Galaxy a13, running Android 14 and One UI 6.1, Android patch level June 2024.

Never expected this to be 32 bit. Not sure how to check that.

**Comment by soupslurpr** [comment] 2024-08-04 03:16
Reading the specs, it isn't 32 bit so I'm not sure why Samsung is blocking installation of apps that don't support it.

**Comment by soupslurpr** [comment] 2024-08-04 03:43
Apparently Samsung decided to make them run a 32-bit OS for some reason.

https://play.google.com/store/apps/details?id=com.finalwire.aida64 should say 32-bit mode in "Instruction Set"

**Comment by samvde** [comment] 2024-08-04 04:09
Yes,  I can confirm. Here I am thinking 32 bit was athing of a decade ago. Not for arm I guess. 

So this is the issue,  the patched apk worked. 

Not sure if you can/want to bring this to the release version, understand if you won't.

Many thanks for the rapid troubleshooting!

**Comment by soupslurpr** [comment] 2024-08-04 05:09
I technically could re-enable it for AppVerifier as it isn't an issue for it but its unfortunate that Samsung is doing this. Running a 32-bit OS reduces security.

**Comment by soupslurpr** [comment] 2025-01-17 01:50
@samvde AppVerifier 0.8.2 adds armeabi-v7a and x86 support back (32-bit).
